<?php

//[services]------------------------------------------------------------------------------------------------------------
$request = service('Request');
$bootstrap = service('Bootstrap');
$dates = service('Dates');
$strings = service('strings');
$authentication = service('authentication');
$server = service("server");
$f = service("forms", array("lang" => "Iris_Patients."));
//[models]--------------------------------------------------------------------------------------------------------------
//[vars]----------------------------------------------------------------------------------------------------------------
$row = $model->getPatient($oid);
$r["patient"] = $row["patient"];
$r["fhir_id"] = $row["fhir_id"];
$r["active"] = $row["active"];
$r["document_type"] = $row["document_type"];
$r["document_number"] = $row["document_number"];
$r["document_issued_place"] = $row["document_issued_place"];
$r["first_name"] = $row["first_name"];
$r["middle_name"] = $row["middle_name"];
$r["first_surname"] = $row["first_surname"];
$r["second_surname"] = $row["second_surname"];
$r["full_name"] = $row["full_name"];
$r["gender"] = $row["gender"];
$r["birth_date"] = $row["birth_date"];
$r["birth_place"] = $row["birth_place"];
$r["marital_status"] = $row["marital_status"];
$r["primary_phone"] = $row["primary_phone"];
$r["secondary_phone"] = $row["secondary_phone"];
$r["email"] = $row["email"];
$r["full_address"] = $row["full_address"];
$r["neighborhood"] = $row["neighborhood"];
$r["city"] = $row["city"];
$r["state"] = $row["state"];
$r["postal_code"] = $row["postal_code"];
$r["country"] = $row["country"];
$r["residence_area"] = $row["residence_area"];
$r["socioeconomic_stratum"] = $row["socioeconomic_stratum"];
$r["emergency_contact_name"] = $row["emergency_contact_name"];
$r["emergency_contact_relationship"] = $row["emergency_contact_relationship"];
$r["emergency_contact_phone"] = $row["emergency_contact_phone"];
$r["health_insurance"] = $row["health_insurance"];
$r["health_regime"] = $row["health_regime"];
$r["affiliation_type"] = $row["affiliation_type"];
$r["ethnicity"] = $row["ethnicity"];
$r["special_population"] = $row["special_population"];
$r["has_diabetes"] = $row["has_diabetes"];
$r["has_hypertension"] = $row["has_hypertension"];
$r["family_history_glaucoma"] = $row["family_history_glaucoma"];
$r["family_history_diabetes"] = $row["family_history_diabetes"];
$r["family_history_retinopathy"] = $row["family_history_retinopathy"];
$r["previous_eye_surgeries"] = $row["previous_eye_surgeries"];
$r["blood_type"] = $row["blood_type"];
$r["allergies"] = $row["allergies"];
$r["current_medications"] = $row["current_medications"];
$r["primary_language"] = $row["primary_language"];
$r["data_consent"] = $row["data_consent"];
$r["accepts_communications"] = $row["accepts_communications"];
$r["profile_photo"] = $row["profile_photo"];
$r["observations"] = $row["observations"];
$r["created_by"] = $row["created_by"];
$r["updated_by"] = $row["updated_by"];
$r["deleted_by"] = $row["deleted_by"];
$r["created_at"] = $row["created_at"];
$r["updated_at"] = $row["updated_at"];
$r["deleted_at"] = $row["deleted_at"];
$back = $f->get_Value("back", $server->get_Referer());
//[Fields]-----------------------------------------------------------------------------
$f->fields["patient"] = $f->get_FieldView("patient", array("value" => $r["patient"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["fhir_id"] = $f->get_FieldView("fhir_id", array("value" => $r["fhir_id"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["active"] = $f->get_FieldView("active", array("value" => $r["active"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["document_type"] = $f->get_FieldView("document_type", array("value" => $r["document_type"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["document_number"] = $f->get_FieldView("document_number", array("value" => $r["document_number"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["document_issued_place"] = $f->get_FieldView("document_issued_place", array("value" => $r["document_issued_place"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["first_name"] = $f->get_FieldView("first_name", array("value" => $r["first_name"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["middle_name"] = $f->get_FieldView("middle_name", array("value" => $r["middle_name"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["first_surname"] = $f->get_FieldView("first_surname", array("value" => $r["first_surname"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["second_surname"] = $f->get_FieldView("second_surname", array("value" => $r["second_surname"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["full_name"] = $f->get_FieldView("full_name", array("value" => $r["full_name"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["gender"] = $f->get_FieldView("gender", array("value" => $r["gender"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["birth_date"] = $f->get_FieldView("birth_date", array("value" => $r["birth_date"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["birth_place"] = $f->get_FieldView("birth_place", array("value" => $r["birth_place"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["marital_status"] = $f->get_FieldView("marital_status", array("value" => $r["marital_status"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["primary_phone"] = $f->get_FieldView("primary_phone", array("value" => $r["primary_phone"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["secondary_phone"] = $f->get_FieldView("secondary_phone", array("value" => $r["secondary_phone"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["email"] = $f->get_FieldView("email", array("value" => $r["email"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["full_address"] = $f->get_FieldView("full_address", array("value" => $r["full_address"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["neighborhood"] = $f->get_FieldView("neighborhood", array("value" => $r["neighborhood"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["city"] = $f->get_FieldView("city", array("value" => $r["city"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["state"] = $f->get_FieldView("state", array("value" => $r["state"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["postal_code"] = $f->get_FieldView("postal_code", array("value" => $r["postal_code"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["country"] = $f->get_FieldView("country", array("value" => $r["country"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["residence_area"] = $f->get_FieldView("residence_area", array("value" => $r["residence_area"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["socioeconomic_stratum"] = $f->get_FieldView("socioeconomic_stratum", array("value" => $r["socioeconomic_stratum"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["emergency_contact_name"] = $f->get_FieldView("emergency_contact_name", array("value" => $r["emergency_contact_name"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["emergency_contact_relationship"] = $f->get_FieldView("emergency_contact_relationship", array("value" => $r["emergency_contact_relationship"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["emergency_contact_phone"] = $f->get_FieldView("emergency_contact_phone", array("value" => $r["emergency_contact_phone"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["health_insurance"] = $f->get_FieldView("health_insurance", array("value" => $r["health_insurance"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["health_regime"] = $f->get_FieldView("health_regime", array("value" => $r["health_regime"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["affiliation_type"] = $f->get_FieldView("affiliation_type", array("value" => $r["affiliation_type"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["ethnicity"] = $f->get_FieldView("ethnicity", array("value" => $r["ethnicity"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["special_population"] = $f->get_FieldView("special_population", array("value" => $r["special_population"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["has_diabetes"] = $f->get_FieldView("has_diabetes", array("value" => $r["has_diabetes"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["has_hypertension"] = $f->get_FieldView("has_hypertension", array("value" => $r["has_hypertension"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["family_history_glaucoma"] = $f->get_FieldView("family_history_glaucoma", array("value" => $r["family_history_glaucoma"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["family_history_diabetes"] = $f->get_FieldView("family_history_diabetes", array("value" => $r["family_history_diabetes"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["family_history_retinopathy"] = $f->get_FieldView("family_history_retinopathy", array("value" => $r["family_history_retinopathy"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["previous_eye_surgeries"] = $f->get_FieldView("previous_eye_surgeries", array("value" => $r["previous_eye_surgeries"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["blood_type"] = $f->get_FieldView("blood_type", array("value" => $r["blood_type"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["allergies"] = $f->get_FieldView("allergies", array("value" => $r["allergies"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["current_medications"] = $f->get_FieldView("current_medications", array("value" => $r["current_medications"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["primary_language"] = $f->get_FieldView("primary_language", array("value" => $r["primary_language"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["data_consent"] = $f->get_FieldView("data_consent", array("value" => $r["data_consent"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["accepts_communications"] = $f->get_FieldView("accepts_communications", array("value" => $r["accepts_communications"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["profile_photo"] = $f->get_FieldView("profile_photo", array("value" => $r["profile_photo"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["observations"] = $f->get_FieldView("observations", array("value" => $r["observations"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["created_by"] = $f->get_FieldView("created_by", array("value" => $r["created_by"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["updated_by"] = $f->get_FieldView("updated_by", array("value" => $r["updated_by"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["deleted_by"] = $f->get_FieldView("deleted_by", array("value" => $r["deleted_by"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["created_at"] = $f->get_FieldView("created_at", array("value" => $r["created_at"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["updated_at"] = $f->get_FieldView("updated_at", array("value" => $r["updated_at"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["deleted_at"] = $f->get_FieldView("deleted_at", array("value" => $r["deleted_at"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["cancel"] = $f->get_Cancel("cancel", array("href" => $back, "text" => lang("App.Cancel"), "type" => "secondary", "proportion" => "col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 padding-right"));
$f->fields["edit"] = $f->get_Button("edit", array("href" => "/iris/patients/edit/" . $oid, "text" => lang("App.Edit"), "class" => "btn btn-secondary", "proportion" => "col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 padding-right"));
//[Groups]-----------------------------------------------------------------------------
$f->groups["g1"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["patient"] . $f->fields["fhir_id"] . $f->fields["active"])));
$f->groups["g2"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["document_type"] . $f->fields["document_number"] . $f->fields["document_issued_place"])));
$f->groups["g3"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["first_name"] . $f->fields["middle_name"] . $f->fields["first_surname"])));
$f->groups["g4"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["second_surname"] . $f->fields["gender"])));
$f->groups["g5"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["birth_date"] . $f->fields["birth_place"] . $f->fields["marital_status"])));
$f->groups["g6"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["primary_phone"] . $f->fields["secondary_phone"] . $f->fields["email"])));
$f->groups["g7"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["full_address"] . $f->fields["neighborhood"] . $f->fields["city"])));
$f->groups["g8"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["state"] . $f->fields["postal_code"] . $f->fields["country"])));
$f->groups["g9"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["residence_area"] . $f->fields["socioeconomic_stratum"] . $f->fields["emergency_contact_name"])));
$f->groups["g10"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["emergency_contact_relationship"] . $f->fields["emergency_contact_phone"] . $f->fields["health_insurance"])));
$f->groups["g11"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["health_regime"] . $f->fields["affiliation_type"] . $f->fields["ethnicity"])));
$f->groups["g12"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["special_population"] . $f->fields["has_diabetes"] . $f->fields["has_hypertension"])));
$f->groups["g13"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["family_history_glaucoma"] . $f->fields["family_history_diabetes"] . $f->fields["family_history_retinopathy"])));
$f->groups["g14"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["previous_eye_surgeries"] . $f->fields["blood_type"] . $f->fields["allergies"])));
$f->groups["g15"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["current_medications"] . $f->fields["primary_language"] . $f->fields["data_consent"])));
$f->groups["g16"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["accepts_communications"] . $f->fields["profile_photo"] . $f->fields["observations"])));
$f->groups["g17"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["created_by"] . $f->fields["updated_by"] . $f->fields["deleted_by"])));
$f->groups["g18"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["created_at"] . $f->fields["updated_at"] . $f->fields["deleted_at"])));
//[Buttons]-----------------------------------------------------------------------------
$f->groups["gy"] = $f->get_GroupSeparator();
$f->groups["gz"] = $f->get_Buttons(array("fields" => $f->fields["edit"] . $f->fields["cancel"]));
//[build]---------------------------------------------------------------------------------------------------------------
echo($f);
?>