<?php
$f->set_ValidationRule("model","trim|required");
//$f->set_ValidationRule("code","trim|required");
$f->set_ValidationRule("name","trim|required");
$f->set_ValidationRule("description","trim|required");
$f->set_ValidationRule("country","trim|required");
//$f->set_ValidationRule("regulatory_framework","trim|required");
$f->set_ValidationRule("uses_credits","trim|required");
//$f->set_ValidationRule("hours_per_credit","trim|required");
//$f->set_ValidationRule("credit_calculation_formula","trim|required");
$f->set_ValidationRule("requires_theoretical_hours","trim|required");
$f->set_ValidationRule("requires_practical_hours","trim|required");
$f->set_ValidationRule("requires_independent_hours","trim|required");
$f->set_ValidationRule("requires_total_hours","trim|required");
//$f->set_ValidationRule("validation_rules","trim|required");
//$f->set_ValidationRule("configuration","trim|required");
$f->set_ValidationRule("is_active","trim|required");
//$f->set_ValidationRule("created_at","trim|required");
//$f->set_ValidationRule("updated_at","trim|required");
//$f->set_ValidationRule("deleted_at","trim|required");
?>