<?php
$mca = model("App\Modules\Crm\Models\Crm_Agents");
$row = $mca->find($oid);
$code = "<style>\n";
$code .= "\t\t.time-label {\n";
$code .= "\t\t\t\tdisplay: block;\n";
$code .= "\t\t\t\tcolor: #adb8c2;\n";
$code .= "\t\t\t\tfont-size: 1rem;\n";
$code .= "\t\t\t\tfont-weight: bold;\n";
$code .= "\t\t\t\tpadding: 0.25rem;\n";
$code .= "\t\t}\n";
$code .= "\n";
$code .= "\t\t.time-value {\n";
$code .= "\t\t\t\tborder-top: 1px solid #ebeff2;\n";
$code .= "\t\t\t\tbackground: #f7f8fa;\n";
$code .= "\t\t\t\toverflow: auto;\n";
$code .= "\t\t\t\tpadding: 0.25rem;\n";
$code .= "\t\t\t\tfont-size: 1rem;\n";
$code .= "\t\t\t\tcolor: #59687f;\n";
$code .= "\t\t\t\tfont-weight: bold;\n";
$code .= "\t\t}\n";
$code .= "</style>\n";
$code .= "<div class=\"card\tmb-3 w-100 mb-3\">\n";
$code .= "\t\t<div class=\"card-header\">\n";
$code .= "\t\t\t\t<h2 class=\"card-header-title p-1\tm-0 opacity-3\">Horario</h2>\n";
$code .= "\t\t</div>\n";
$code .= "\n";
$code .= "\t\t<div class=\"card-body p-3 \">\n";
$code .= "\t\t\t\t<div class=\"row text-center d-block px-3\">\n";
$code .= "\t\t\t\t\t\t<div class=\" col-12 text-center time-label\n";
$code .= "\t\t\t\t\">\n";
$code .= "\t\t\t\t\t\t\t\tTurno de la mañana\n";
$code .= "\t\t\t\t\t\t</div>\n";
$code .= "\t\t\t\t</div>\n";
$code .= "\t\t\t\t<div class=\"row text-center d-flex px-3\">\n";
$code .= "\t\t\t\t\t\t<div class=\"col-6 text-center time-value\">\n";
$code .= "\t\t\t\t\t\t\t\t" . $row["morning_shift_start"] . "\n";
$code .= "\t\t\t\t\t\t</div>\n";
$code .= "\t\t\t\t\t\t<div class=\"col-6 text-center time-value\">\n";
$code .= "\t\t\t\t\t\t\t\t" . $row["morning_shift_end"] . "\n";
$code .= "\t\t\t\t\t\t</div>\n";
$code .= "\t\t\t\t</div>\n";
$code .= "\t\t\t\t<div class=\"row text-center d-block px-3\">\n";
$code .= "\t\t\t\t\t\t<div class=\"col-12 text-center time-label\">\n";
$code .= "\t\t\t\t\t\t\t\tTurno de la tarde\n";
$code .= "\t\t\t\t\t\t</div>\n";
$code .= "\t\t\t\t</div>\n";
$code .= "\t\t\t\t<div class=\"row text-center d-flex px-3\">\n";
$code .= "\t\t\t\t\t\t<div class=\"col-6 text-center time-value\">\n";
$code .= "\t\t\t\t\t\t\t\t" . $row["afternoon_shift_start"] . "\n";
$code .= "\t\t\t\t\t\t</div>\n";
$code .= "\t\t\t\t\t\t<div class=\"col-6 text-center time-value\">\n";
$code .= "\t\t\t\t\t\t\t\t" . $row["afternoon_shift_end"] . "\n";
$code .= "\t\t\t\t\t\t</div>\n";
$code .= "\t\t\t\t</div>\n";
$code .= "\t\t</div>\n";
$code .= "</div>\n";
echo($code);
?>