<?php

$strings = service("strings");
/** @var string $module */
$ucf_module = $strings->get_Ucfirst($module);
$lc_module = $strings->get_Strtolower($module);

$code = "<?php\n";
$code .= "/**\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "* █ ░FRAMEWORK\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t2023-11-26 00:29:34\n";
$code .= "* █ ░█▀▀█ █▀▀█ █▀▀▄ █▀▀ ░█─░█ ─▀─ █▀▀▀ █▀▀▀ █▀▀ [App\Modules}\\$ucf_module\Controllers\\$ucf_module.php]\n";
$code .= "* █ ░█─── █──█ █──█ █▀▀ ░█▀▀█ ▀█▀ █─▀█ █─▀█ ▀▀█ Copyright 2023 - CloudEngine S.A.S., Inc. <admin@cgine.com>\n";
$code .= "* █ ░█▄▄█ ▀▀▀▀ ▀▀▀─ ▀▀▀ ░█─░█ ▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀ Para obtener información completa sobre derechos de autor y licencia,\n";
$code .= "* █\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t consulte la LICENCIA archivo que se distribuyó con este código fuente.\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "* █ EL SOFTWARE SE PROPORCIONA -TAL CUAL-, SIN GARANTÍA DE NINGÚN TIPO, EXPRESA O\n";
$code .= "* █ IMPLÍCITA, INCLUYENDO PERO NO LIMITADO A LAS GARANTÍAS DE COMERCIABILIDAD,\n";
$code .= "* █ APTITUD PARA UN PROPÓSITO PARTICULAR Y NO INFRACCIÓN. EN NINGÚN CASO SERÁ\n";
$code .= "* █ LOS AUTORES O TITULARES DE LOS DERECHOS DE AUTOR SERÁN RESPONSABLES DE CUALQUIER\n";
$code .= "* █ RECLAMO, DAÑOS U OTROS RESPONSABILIDAD, YA SEA EN UNA ACCIÓN DE CONTRATO,\n";
$code .= "* █ AGRAVIO O DE OTRO MODO, QUE SURJA DESDE, FUERA O EN RELACIÓN CON EL SOFTWARE\n";
$code .= "* █ O EL USO U OTROS NEGOCIACIONES EN EL SOFTWARE.\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "* █ @Author Jose Alexis Correa Valencia <jalexiscv@gmail.com>\n";
$code .= "* █ @link https://www.codehiggs.com\n";
$code .= "* █ @Version 2.0.0 @since PHP 7, PHP 8\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "* █ Datos recibidos desde el controlador - @ModuleController\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "* █ Ninguno\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "**/\n";
$code .= "\n";
$code .= "namespace App\Modules\\$ucf_module\\Controllers;\n";
$code .= "\n";
$code .= "use App\Controllers\ModuleController;\n";
$code .= "\n";
$code .= "class $ucf_module extends ModuleController\n";
$code .= "{\n";
$code .= "\n";
$code .= "\n";
$code .= "\t\tpublic function __construct()\n";
$code .= "\t\t{\n";
$code .= "\t\t\t\tparent::__construct();\n";
$code .= "\t\t\t\t\$this->module = 'App\Modules\\$ucf_module';\n";
$code .= "\t\t\t\thelper(\$this->module . '\Helpers\\$ucf_module');\n";
$code .= "\t\t\t\t\$this->prefix = '$lc_module';\n";
$code .= "\t\t\t\t\$this->views = \$this->module . '\Views';\n";
$code .= "\t\t\t\t\$this->viewer = \$this->views . '\index';\n";
$code .= "\t\t\t\t\$this->component = \$this->views . '\Home';\n";
$code .= "\t\t}\n";
$code .= "\n";
$code .= "\t\tpublic function index()\n";
$code .= "\t\t{\n";
$code .= "\t\t\t\t\$alias = safe_get_alias();\n";
$code .= "\t\t\t\t\$url = base_url(\"$lc_module/home/{\$alias}.html\");\n";
$code .= "\t\t\t\treturn (redirect()->to(\$url));\n";
$code .= "\t\t}\n";
$code .= "\n";
$code .= "\t\tpublic function home(string \$rnd = \"index\")\n";
$code .= "\t\t{\n";
$code .= "\t\t\t\t\$this->oid = null;\n";
$code .= "\t\t\t\t\$this->prefix = \"{\$this->prefix}-home\";\n";
$code .= "\t\t\t\treturn (view(\$this->viewer, \$this->get_Array()));\n";
$code .= "\t\t}\n";
$code .= "\n";
$code .= "\n";
$code .= "\t\tpublic function denied(string \$rnd = null): string\n";
$code .= "\t\t{\n";
$code .= "\t\t\t\t\$this->oid = null;\n";
$code .= "\t\t\t\t\$this->prefix = \"{\$this->prefix}-denied\";\n";
$code .= "\t\t\t\treturn (view(\$this->viewer, \$this->get_Array()));\n";
$code .= "\t\t}\n";
$code .= "\n";
$code .= "\t\tpublic function semantic(string \$oid)\n";
$code .= "\t\t{\n";
$code .= "\t\t\t\t\$this->oid = \$oid;\n";
$code .= "\t\t\t\t\$this->prefix = \"{\$this->prefix}-home\";\n";
$code .= "\t\t\t\treturn (view(\$this->viewer, \$this->get_Array()));\n";
$code .= "\t\t}\n";
$code .= "\n";
$code .= "\n";
$code .= "}\n";
$code .= "\n";
$code .= "?>";
echo($code);
?>