<?php
$strings = service("strings");
/** @var string $module */
$ucf_module = $strings->get_Ucfirst($module);
$lc_module = $strings->get_Strtolower($module);

$code = "<?php\n";
$code .= "/**\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "* █ ░FRAMEWORK\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t2023-11-26 00:29:34\n";
$code .= "* █ ░█▀▀█ █▀▀█ █▀▀▄ █▀▀ ░█─░█ ─▀─ █▀▀▀ █▀▀▀ █▀▀ [App\Modules\Development\Config\Routes.php]\n";
$code .= "* █ ░█─── █──█ █──█ █▀▀ ░█▀▀█ ▀█▀ █─▀█ █─▀█ ▀▀█ Copyright 2023 - CloudEngine S.A.S., Inc. <admin@cgine.com>\n";
$code .= "* █ ░█▄▄█ ▀▀▀▀ ▀▀▀─ ▀▀▀ ░█─░█ ▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀ Para obtener información completa sobre derechos de autor y licencia,\n";
$code .= "* █\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t consulte la LICENCIA archivo que se distribuyó con este código fuente.\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "* █ EL SOFTWARE SE PROPORCIONA -TAL CUAL-, SIN GARANTÍA DE NINGÚN TIPO, EXPRESA O\n";
$code .= "* █ IMPLÍCITA, INCLUYENDO PERO NO LIMITADO A LAS GARANTÍAS DE COMERCIABILIDAD,\n";
$code .= "* █ APTITUD PARA UN PROPÓSITO PARTICULAR Y NO INFRACCIÓN. EN NINGÚN CASO SERÁ\n";
$code .= "* █ LOS AUTORES O TITULARES DE LOS DERECHOS DE AUTOR SERÁN RESPONSABLES DE CUALQUIER\n";
$code .= "* █ RECLAMO, DAÑOS U OTROS RESPONSABILIDAD, YA SEA EN UNA ACCIÓN DE CONTRATO,\n";
$code .= "* █ AGRAVIO O DE OTRO MODO, QUE SURJA DESDE, FUERA O EN RELACIÓN CON EL SOFTWARE\n";
$code .= "* █ O EL USO U OTROS NEGOCIACIONES EN EL SOFTWARE.\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "* █ @Author Jose Alexis Correa Valencia <jalexiscv@gmail.com>\n";
$code .= "* █ @link https://www.codehiggs.com\n";
$code .= "* █ @Version 2.0.0 @since PHP 7, PHP 8\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "* █ Datos recibidos desde el controlador - @ModuleController\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "* █ Ninguno\n";
$code .= "* █ -------------------------------------------------------------------------------------------------------------------\n";
$code .= "**/\n";
$code .= "\n";
$code .= "use Config\Services;\n";
$code .= "\n";
$code .= "// [services] ----------------------------------------------------------------------------------------------------------\n";
$code .= "\$platform = service('platform');\n";
$code .= "\n";
$code .= "// [vars] --------------------------------------------------------------------------------------------------------------\n";
$code .= "if (\$platform->get_CandidateModule(__FILE__)) {\n";
$code .= "\t\t\$routes = \$routes ?? Services::routes(true);\n";
$code .= "\t\t\$module = '{$lc_module}';\n";
$code .= "\t\t\$namespace = 'App\Modules\\".$ucf_module."\\Controllers';\n";
$code .= "\t\t\$authorized = \$platform->get_AuthorizedModule(\$module);\n";
$code .= "\t\t\$routes->group(\$module, ['namespace' => \$namespace], function (\$subroutes) use (\$authorized) {\n";
$code .= "\t\t\t\tif (\$authorized === 'authorized') {\n";
$code .= "\t\t\t\t\t\t\$subroutes->add('', '{$ucf_module}::index');\n";
$code .= "\t\t\t\t\t\t\$subroutes->add('home', '{$ucf_module}::index');\n";
$code .= "\t\t\t\t\t\t\$subroutes->add('home/(:any)', '{$ucf_module}::home/\$1');\n";
$code .= "\t\t\t\t\t\t\$subroutes->add('(:any)/(:any)/(:any)', 'Router::route/\$1/\$2/\$3');\n";
$code .= "\t\t\t\t} else {\n";
$code .= "\t\t\t\t\t\t\$subroutes->add('/', '{$ucf_module}::denied');\n";
$code .= "\t\t\t\t\t\t\$subroutes->add('(:any)', '{$ucf_module}::denied');\n";
$code .= "\t\t\t\t}\n";
$code .= "\t\t});\n";
$code .= "}\n";
$code .= "?>\n";
echo($code);
?>