<?php
/** @var string $registration */
//[services]------------------------------------------------------------------------------------------------------------
$request = service('request');
$bootstrap = service('bootstrap');
$dates = service('dates');
$strings = service('strings');
$authentication = service('authentication');
$f = service("forms", array("lang" => "Sie_Registrations."));
//[models]--------------------------------------------------------------------------------------------------------------
$mregistrations = model("App\Modules\Sie\Models\Sie_Registrations");
$mprograms = model("App\Modules\Sie\Models\Sie_Programs");
$mcountries = model("App\Modules\Sie\Models\Sie_Countries");
$mregions = model("App\Modules\Sie\Models\Sie_Regions");
$mcities = model("App\Modules\Sie\Models\Sie_Cities");
//[vars]----------------------------------------------------------------------------------------------------------------
$row = $mregistrations->getRegistration($registration);
$r["registration"] = $f->get_Value("registration", @$row["registration"]); 
$r["first_name"] = $f->get_Value("first_name", @$row["first_name"]);
$r["second_name"] = $f->get_Value("second_name", @$row["second_name"]);
$r["first_surname"] = $f->get_Value("first_surname", @$row["first_surname"]);
$r["second_surname"] = $f->get_Value("second_surname", @$row["second_surname"]);
$r["identification_type"] = $f->get_Value("identification_type", @$row["identification_type"]);
$r["identification_number"] = $f->get_Value("identification_number", @$row["identification_number"]);
$r["birth_date"] = $f->get_Value("birth_date", @$row["birth_date"]);
$r["birth_country"] = (@$row["birth_country"] ?? "CO") . ": " . users_get_textual_country((@$row["birth_country"] ?? "CO"));
$r["birth_region"] = (@$row["birth_region"] ?? "076") . ": " . users_get_textual_region((@$row["country_of_region"] ?? "076"));
$r["birth_city"] = @$row["birth_city"] . ": " . users_get_textual_city(@$row["birth_city"]);
$r["gender"] = $f->get_Value("gender", @$row["gender"]);
$r["email_address"] = $f->get_Value("email_address", @$row["email_address"]);
$r["phone"] = $f->get_Value("phone", @$row["phone"]);
$r["mobile"] = $f->get_Value("mobile", @$row["mobile"]);
$r["residence_country"] = (@$row["residence_country"] ?? "CO") . ": " . users_get_textual_country((@$row["residence_country"] ?? "CO"));
$r["residence_region"] = (@$row["residence_region"] ?? "076") . ": " . users_get_textual_region((@$row["residence_region"] ?? "076"));
$r["residence_city"] = @$row["residence_city"] . ": " . users_get_textual_city(@$row["residence_city"]);
$r["address"] = $f->get_Value("address", @$row["address"]);
$r["neighborhood"] = $f->get_Value("neighborhood", @$row["neighborhood"]);
$r["area"] = $f->get_Value("area", @$row["area"]);
$r["stratum"] = $f->get_Value("stratum", @$row["stratum"]);
$r["transport_method"] = $f->get_Value("transport_method", @$row["transport_method"]);
$r["sisben_group"] = $f->get_Value("sisben_group", @$row["sisben_group"]);
$r["sisben_subgroup"] = $f->get_Value("sisben_subgroup", @$row["sisben_subgroup"]);
$r["document_issue_place"] = $f->get_Value("document_issue_place", @$row["document_issue_place"]);
$r["blood_type"] = $f->get_Value("blood_type", @$row["blood_type"]);
$r["marital_status"] = $f->get_Value("marital_status", @$row["marital_status"]);
$r["number_children"] = $f->get_Value("number_children", @$row["number_children"]);
$r["military_card"] = $f->get_Value("military_card", @$row["military_card"]);
$r["ars"] = $f->get_Value("ars", @$row["ars"]);
$r["insurer"] = $f->get_Value("insurer", @$row["insurer"]);
$r["eps"] = $f->get_Value("eps", @$row["eps"]);
$r["education_level"] = $f->get_Value("education_level", @$row["education_level"]);
$r["occupation"] = $f->get_Value("occupation", @$row["occupation"]);
$r["health_regime"] = $f->get_Value("health_regime", @$row["health_regime"]);
$r["document_issue_date"] = $f->get_Value("document_issue_date", @$row["document_issue_date"]);
$r["saber11"] = $f->get_Value("saber11", @$row["saber11"]);
$r["observations"] = $f->get_Value("observations", @$row["observations"]);
$r["status"] = $f->get_Value("status", @$row["status"]);
$r["period"] = $f->get_Value("period", @$row["period"]);
$r["journey"] = $f->get_Value("journey", "".@$row["journey"].": " . users_get_textual_journey(@$row["journey"]));
$r["program"] = @$row["program"] . ": " . users_get_textual_program(@$row["program"]);
$back = "/sie/students/list/" . lpk();
$regions_birth = array(array("value" => "", "label" => "Seleccione una región"),);
$cities_birth = array(array("value" => "", "label" => "Seleccione una ciudad"),);
//[fields]--------------------------------------------------------------------------------------------------------------
$f->add_HiddenField("tab", "1");
$f->fields["registration"] = $f->get_FieldView("registration", array("value" => $r["registration"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12", "readonly" => "readonly"));
$f->fields["first_name"] = $f->get_FieldView("first_name", array("value" => $r["first_name"], "proportion" => "col-xl-3 col-lg-3 col-md-3 col-sm-12 col-12"));
$f->fields["second_name"] = $f->get_FieldView("second_name", array("value" => $r["second_name"], "proportion" => "col-xl-3 col-lg-3 col-md-3 col-sm-12 col-12"));
$f->fields["first_surname"] = $f->get_FieldView("first_surname", array("value" => $r["first_surname"], "proportion" => "col-xl-3 col-lg-3 col-md-3 col-sm-12 col-12"));
$f->fields["second_surname"] = $f->get_FieldView("second_surname", array("value" => $r["second_surname"], "proportion" => "col-xl-3 col-lg-3 col-md-3 col-sm-12 col-12"));
$f->fields["identification_type"] = $f->get_FieldView("identification_type", array("selected" => @$r["identification_type"], "data" => LIST_IDENTIFICATION_TYPES, "proportion" => "col-md-3 col-sm-12 col-12"));
$f->fields["identification_number"] = $f->get_FieldView("identification_number", array("value" => @$r["identification_number"], "proportion" => "col-md-3 col-sm-12 col-12"));
$f->fields["identification_place"] = $f->get_FieldView("identification_place", array("value" => @$r["identification_place"], "proportion" => "col-md-3 col-sm-12 col-12"));
$f->fields["identification_date"] = $f->get_FieldView("identification_date", array("value" => @$r["identification_date"], "proportion" => "col-md-3 col-sm-12 col-12"));
$f->fields["email_address"] = $f->get_FieldView("email_address", array("value" => $r["email_address"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["phone"] = $f->get_FieldView("phone", array("value" => $r["phone"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["mobile"] = $f->get_FieldView("mobile", array("value" => $r["mobile"], "proportion" => "col-xl-4 col-lg-6 col-md-4 col-sm-12 col-12"));
$f->fields["gender"] = $f->get_FieldView("gender", array("value" => $r["gender"], "data" => LIST_SEX, "proportion" => "col-md-4 col-sm-12 col-12"));
$f->fields["blood_type"] = $f->get_FieldView("blood_type", array("value" => $r["blood_type"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["birth_date"] = $f->get_FieldView("birth_date", array("value" => $r["birth_date"], "proportion" => "col-md-6 col-sm-12 col-12"));
$f->fields["birth_country"] = $f->get_FieldView("birth_country", array("value" => $r["birth_country"], "proportion" => "col-md-6 col-sm-12 col-12"));
$f->fields["birth_region"] = $f->get_FieldView("birth_region", array("value" => $r["birth_region"], "proportion" => "col-md-6 col-sm-12 col-12"));
$f->fields["birth_city"] = $f->get_FieldView("birth_city", array("value" => $r["birth_city"], "proportion" => "col-md-6 col-sm-12 col-12"));
$f->fields["residence_country"] = $f->get_FieldView("residence_country", array("value" => $r["residence_country"], "proportion" => "col-md-4 col-sm-12 col-12"));
$f->fields["residence_region"] = $f->get_FieldView("residence_region", array("value" => $r["residence_region"], "proportion" => "col-md-4 col-sm-12 col-12"));
$f->fields["residence_city"] = $f->get_FieldView("residence_city", array("value" => $r["residence_city"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["address"] = $f->get_FieldView("address", array("value" => $r["address"], "proportion" => "col-md-6 col-sm-12 col-12"));
$f->fields["neighborhood"] = $f->get_FieldView("neighborhood", array("value" => $r["neighborhood"], "proportion" => "col-md-6 col-sm-12 col-12"));
$f->fields["area"] = $f->get_FieldView("area", array("value" => $r["area"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["stratum"] = $f->get_FieldView("stratum", array("value" => $r["stratum"], "data" => LIST_STRATUMS, "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["transport_method"] = $f->get_FieldView("transport_method", array("value" => $r["transport_method"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["sisben_group"] = $f->get_FieldView("sisben_group", array("value" => $r["sisben_group"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["sisben_subgroup"] = $f->get_FieldView("sisben_subgroup", array("value" => $r["sisben_subgroup"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["document_issue_place"] = $f->get_FieldView("document_issue_place", array("value" => $r["document_issue_place"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["period"] = $f->get_FieldView("period", array("value" => $r["period"], "data" => LIST_PERIODS, "proportion" => "col-md-4 col-sm-12 col-12"));
$f->fields["journey"] = $f->get_FieldView("journey", array("value" => $r["journey"], "data" => LIST_JOURNEYS, "proportion" => "col-md-4 col-sm-12 col-12"));
$f->fields["program"] = $f->get_FieldView("program", array("value" => $r["program"], "proportion" => "col-12"));
$f->fields["marital_status"] = $f->get_FieldView("marital_status", array("value" => $r["marital_status"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["number_children"] = $f->get_FieldView("number_children", array("value" => $r["number_children"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["military_card"] = $f->get_FieldView("military_card", array("value" => $r["military_card"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["ars"] = $f->get_FieldView("ars", array("value" => $r["ars"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["insurer"] = $f->get_FieldView("insurer", array("value" => $r["insurer"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["eps"] = $f->get_FieldView("eps", array("value" => $r["eps"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["education_level"] = $f->get_FieldView("education_level", array("value" => $r["education_level"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["occupation"] = $f->get_FieldView("occupation", array("value" => $r["occupation"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["health_regime"] = $f->get_FieldView("health_regime", array("value" => $r["health_regime"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["document_issue_date"] = $f->get_FieldView("document_issue_date", array("value" => $r["document_issue_date"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["saber11"] = $f->get_FieldView("saber11", array("value" => $r["saber11"], "proportion" => "col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12"));
$f->fields["observations"] = $f->get_FieldViewArea("observations", array("value" => $r["observations"], "proportion" => "col-12"));
$f->fields["status"] = $f->get_FieldView("status", array("value" => $r["status"], "data" => LIST_STATUSES, "proportion" => "col-12"));
//[buttons]-------------------------------------------------------------------------------------------------------------
$f->fields["cancel"] = $f->get_Cancel("cancel", array("href" => $back, "text" => lang("App.Continue"), "type" => "secondary", "proportion" => "col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 padding-right"));
$f->fields["submit"] = $f->get_Submit("submit", array("value" => lang("App.Edit"), "proportion" => "col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 padding-left"));
//[groups]----------------------------------------------------------------------------------------------------------------
$f->groups["g02"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["registration"]  . $f->fields["period"] . $f->fields["journey"])));
$f->groups["g03"] = $f->get_Group(array("legend" => "", "fields" => ($f->fields["program"])));
$f->groups["gp026"]=$f->get_Group(array("legend"=>"1. Perfil Personal","fields"=>($f->fields["first_name"].$f->fields["second_name"].$f->fields["first_surname"].$f->fields["second_surname"])));
$f->groups["gp027"]=$f->get_Group(array("legend"=>"","fields" => ($f->fields["identification_type"] . $f->fields["identification_number"] . $f->fields["identification_place"] . $f->fields["identification_date"])));
$f->groups["gp028"]=$f->get_Group(array("legend"=>"","fields"=>($f->fields["email_address"].$f->fields["phone"].$f->fields["mobile"])));
$f->groups["gp029"]=$f->get_Group(array("legend"=>"","fields"=>($f->fields["gender"].$f->fields["blood_type"])));
$f->groups["gp039"]=$f->get_Group(array("legend"=>"1.1. Procedencia","fields"=>($f->fields["birth_date"].$f->fields["birth_country"])));
$f->groups["gp310"]=$f->get_Group(array("legend"=>"","fields"=>($f->fields["birth_region"].$f->fields["birth_city"])));
$f->groups["gp311"]=$f->get_Group(array("legend"=>"1.2. Residencia","fields"=>($f->fields["residence_country"].$f->fields["residence_region"].$f->fields["residence_city"])));
$f->groups["gp312"]=$f->get_Group(array("legend"=>"","fields"=>($f->fields["address"].$f->fields["neighborhood"])));
$f->groups["gp313"]=$f->get_Group(array("legend"=>"","fields"=>($f->fields["area"].$f->fields["stratum"])));
//[buttons]-------------------------------------------------------------------------------------------------------------
//$f->groups["gy"] = $f->get_GroupSeparator();
//$f->groups["gz"] = $f->get_Buttons(array("fields" => $f->fields["cancel"]));
//[build]---------------------------------------------------------------------------------------------------------------
echo($f);
$fid = $f->get_fid();
?>