<?php

namespace Higgs\Database\OCI8;

use Higgs\Database\Forge as BaseForge;

class Forge extends BaseForge
{
    protected $dropIndexStr = 'DROP INDEX %s';
    protected $createDatabaseStr = false;
    protected $createTableIfStr = false;
    protected $dropTableIfStr = false;
    protected $dropDatabaseStr = false;
    protected $unsigned = false;
    protected $null = 'NULL';
    protected $renameTableStr = 'ALTER TABLE %s RENAME TO %s';
    protected $dropConstraintStr = 'ALTER TABLE %s DROP CONSTRAINT %s';
    protected $fkAllowActions = ['CASCADE', 'SET NULL', 'NO ACTION'];

    protected function _alterTable(string $alterType, string $table, $field)
    {
        $sql = 'ALTER TABLE ' . $this->db->escapeIdentifiers($table);
        if ($alterType === 'DROP') {
            $fields = array_map(fn($field) => $this->db->escapeIdentifiers(trim($field)), is_string($field) ? explode(',', $field) : $field);
            return $sql . ' DROP (' . implode(',', $fields) . ') CASCADE CONSTRAINT INVALIDATE';
        }
        if ($alterType === 'CHANGE') {
            $alterType = 'MODIFY';
        }
        $nullableMap = array_column($this->db->getFieldData($table), 'nullable', 'name');
        $sqls = [];
        for ($i = 0, $c = count($field); $i < $c; $i++) {
            if ($alterType === 'MODIFY') {
                $isWantToAddNull = strpos($field[$i]['null'], ' NOT') === false;
                $currentNullAddable = $nullableMap[$field[$i]['name']];
                if ($isWantToAddNull === $currentNullAddable) {
                    $field[$i]['null'] = '';
                }
            }
            if ($field[$i]['_literal'] !== false) {
                $field[$i] = "\n\t" . $field[$i]['_literal'];
            } else {
                $field[$i]['_literal'] = "\n\t" . $this->_processColumn($field[$i]);
                if (!empty($field[$i]['comment'])) {
                    $sqls[] = 'COMMENT ON COLUMN ' . $this->db->escapeIdentifiers($table) . '.' . $this->db->escapeIdentifiers($field[$i]['name']) . ' IS ' . $field[$i]['comment'];
                }
                if ($alterType === 'MODIFY' && !empty($field[$i]['new_name'])) {
                    $sqls[] = $sql . ' RENAME COLUMN ' . $this->db->escapeIdentifiers($field[$i]['name']) . ' TO ' . $this->db->escapeIdentifiers($field[$i]['new_name']);
                }
                $field[$i] = "\n\t" . $field[$i]['_literal'];
            }
        }
        $sql .= ' ' . $alterType . ' ';
        $sql .= count($field) === 1 ? $field[0] : '(' . implode(',', $field) . ')';
        array_unshift($sqls, $sql);
        return $sqls;
    }

    protected function _processColumn(array $field): string
    {
        $constraint = '';
        if ($field['type'] === 'VARCHAR2' && strpos($field['length'], "('") === 0) {
            $constraint = ' CHECK(' . $this->db->escapeIdentifiers($field['name']) . ' IN ' . $field['length'] . ')';
            $field['length'] = '(' . max(array_map('mb_strlen', explode("','", mb_substr($field['length'], 2, -2)))) . ')' . $constraint;
        } elseif (isset($this->primaryKeys['fields']) && count($this->primaryKeys['fields']) === 1 && $field['name'] === $this->primaryKeys['fields'][0]) {
            $field['unique'] = '';
        }
        return $this->db->escapeIdentifiers($field['name']) . ' ' . $field['type'] . $field['length'] . $field['unsigned'] . $field['default'] . $field['auto_increment'] . $field['null'] . $field['unique'];
    }

    protected function _attributeAutoIncrement(array &$attributes, array &$field)
    {
        if (!empty($attributes['AUTO_INCREMENT']) && $attributes['AUTO_INCREMENT'] === true && stripos($field['type'], 'NUMBER') !== false && version_compare($this->db->getVersion(), '12.1', '>=')) {
            $field['auto_increment'] = ' GENERATED BY DEFAULT ON NULL AS IDENTITY';
        }
    }

    protected function _attributeType(array &$attributes)
    {
        switch (strtoupper($attributes['TYPE'])) {
            case 'TINYINT':
                $attributes['CONSTRAINT'] ??= 3;
            case 'SMALLINT':
                $attributes['CONSTRAINT'] ??= 5;
            case 'MEDIUMINT':
                $attributes['CONSTRAINT'] ??= 7;
            case 'INT':
            case 'INTEGER':
                $attributes['CONSTRAINT'] ??= 11;
            case 'BIGINT':
                $attributes['CONSTRAINT'] ??= 19;
            case 'NUMERIC':
                $attributes['TYPE'] = 'NUMBER';
                return;
            case 'BOOLEAN':
                $attributes['TYPE'] = 'NUMBER';
                $attributes['CONSTRAINT'] = 1;
                $attributes['UNSIGNED'] = true;
                $attributes['NULL'] = false;
                return;
            case 'DOUBLE':
                $attributes['TYPE'] = 'FLOAT';
                $attributes['CONSTRAINT'] ??= 126;
                return;
            case 'DATETIME':
            case 'TIME':
                $attributes['TYPE'] = 'DATE';
                return;
            case 'SET':
            case 'ENUM':
            case 'VARCHAR':
                $attributes['CONSTRAINT'] ??= 255;
            case 'TEXT':
            case 'MEDIUMTEXT':
                $attributes['CONSTRAINT'] ??= 4000;
                $attributes['TYPE'] = 'VARCHAR2';
        }
    }

    protected function _dropTable(string $table, bool $ifExists, bool $cascade)
    {
        $sql = parent::_dropTable($table, $ifExists, $cascade);
        if ($sql !== true && $cascade === true) {
            $sql .= ' CASCADE CONSTRAINTS PURGE';
        } elseif ($sql !== true) {
            $sql .= ' PURGE';
        }
        return $sql;
    }

    protected function _dropKeyAsConstraint(string $table, string $constraintName): string
    {
        return "SELECT constraint_name FROM all_constraints WHERE table_name = '" . trim($table, '"') . "' AND index_name = '" . trim($constraintName, '"') . "'";
    }
}