<?php
$mias = model('App\Modules\Intelligence\Models\Intelligence_Ias');
$ia = $mias->get_IaByUser(safe_get_user());
//print_r($ia);
if ($ia) {
    //echo "IA found";
} else {
    $names = array(
        "Aurora",
        "Celeste",
        "Elysia",
        "Seraphina",
        "Valencia",
        "Genevieve",
        "Isadora",
        "Lyra",
        "Amara",
        "Rosalind",
        "Vivienne",
        "Cassandra",
        "Theia",
        "Calypso",
        "Persephone",
        "Aether",
        "Nova",
        "Pixel",
        "Cipher",
        "Vector",
        "Nexus",
        "Echo",
        "Synapse",
        "Qubit",
        "Zenith",
        "Axiom",
        "Luna",
        "Astra",
        "Solara",
        "Gaia",
        "Nyx",
        "Rhea",
        "Iris",
        "Hera",
        "Artemis",
        "Selene",
        "Eos",
        "Aria",
        "Indigo",
        "Juniper",
        "Skylar",
        "Phoenix",
        "Harmony",
        "Verity",
        "Zephyr",
        "Ada",
        "Ava",
        "Clara",
        "Elena",
        "Emma",
        "Grace",
        "Iris",
        "Ivy",
        "Julia",
        "June",
        "Lily",
        "Luna",
        "Maya",
        "Nora",
        "Rose",
        "Ruby",
        "Sofia",
        "Violet",
        "Zoe",
        "Anya",
        "Eden",
        "Isla",
        "Jade",
        "Lyra",
        "Maeve",
        "Nina",
        "Pearl",
        "Sage",
        "Skye",
        "Amara",
        "Asha",
        "Esme",
        "Imani",
        "Kali",
        "Kira",
        "Lin",
        "Lumi",
        "Mila",
        "Zara",
        "Brie",
        "Bryn",
        "Gaia",
        "Jade",
        "Lena",
        "Rhea",
        "Sacha",
        "Thea",
        "Zara",
        "Fawn",
        "Wren"
    );
    $aleatorio = $names[array_rand($names, 1)];
    $d = array(
        "ia" => pk(),
        "tech" => "VERTEX",
        "name" => $aleatorio,
        "description" => "",
        "prompt" => "",
        "user" => safe_get_user(),
        "identification" => "",
        "author" => "SYSTEM",
    );
    $create = $mias->insert($d);
}

require_once("chat.php");
?>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        document.title = "IA";
    });
</script>
