<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8dd58a91cdc1b178461268989750e986
{
    public static $prefixLengthsPsr4 = array(
        'A' =>
            array(
                'Ayeo\\Barcode\\' => 13,
            ),
    );

    public static $prefixDirsPsr4 = array(
        'Ayeo\\Barcode\\' =>
            array(
                0 => __DIR__ . '/..' . '/ayeo/gs1_barcode/src',
            ),
    );

    public static $classMap = array(
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8dd58a91cdc1b178461268989750e986::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8dd58a91cdc1b178461268989750e986::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8dd58a91cdc1b178461268989750e986::$classMap;

        }, null, ClassLoader::class);
    }
}
