<?php

namespace App\Modules\Disa\Models;

use Higgs\Model;

class Disa_Furag extends Model
{

    protected $table = "disa_furag";
    protected $primaryKey = "sigep";
    protected $returnType = "array";
    protected $useSoftDeletes = true;
    protected $allowedFields = [
        "sigep",
        "entidad",
        "tipo_de_informe",
        "orden",
        "clasificacion_organica",
        "naturaleza_juridica",
        "sector",
        "tipo_de vinculacion",
        "departamento",
        "municipio",
        "grupo_par",
        "indice_de_desempeño_institucional",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "política_1_gestion_estratégica_del_talento_humano",
        "política_2_integridad",
        "política_3_planeacion_institucional",
        "política_4_gestion_presupuestal_y_eficiencia_del_gasto_público",
        "política_5_fortalecimiento_organizacional_y_simplificacion_de_pr",
        "política_6_gobierno_digital",
        "política_7_seguridad_digital",
        "política_8_defensa_juridica",
        "política_9_transparencia,_acceso_a_la_informacion_y_lucha_contra",
        "política_10_servicio_al_ciudadano",
        "política_11_racionalizacion_de_trámites",
        "política_12_participacion_ciudadana_en_la_gestion_pública",
        "política_13_seguimiento_y_evaluacion_del_desempeño_institucional",
        "política_14_gestion_documental",
        "política_15_gestion_del_conocimiento",
        "política_16_control_interno",
        "política_17_mejora_normativa",
        "política_18_gestion_de_la_informacion_estadistica",
        "i01talento_humano_calidad_de_la_planeacion_estratégica_del_talen",
        "i02talento_humano_eficiencia_y_eficacia_de_la_seleccion_meritocr",
        "i03talento_humano_desarrollo_y_bienestar_del_talento_humano_en_l",
        "i04talento_humano_desvinculacion_asistida_y_retencion_del_conoci",
        "i05integridad_cambio_cultural_basado_en_la_implementacion_del_co",
        "i06integridad_gestion_adecuada_de_conflictos_de_interés_y_declar",
        "i07integridad_coherencia_entre_la_gestion_de_riesgos_con_el_cont",
        "i08planeacion_planeacion_basada_en_evidencias",
        "i09planeacion_enfoque_en_la_satisfaccion_ciudadana",
        "i10planeacion_formulacion_de_la_política_de_administracion_del_r",
        "i11planeacion_planeacion_participativa",
        "i12planeacion_identificacion_de_mecanismos_para_el_seguimiento,",
        "i81fortalecimiento_organizacional_eficacia_organizacional",
        "i17fortalecimiento_organizacional_gestion_optima_de_los_bienes_y",
        "i18gobierno_digital_empoderamiento_de_los_ciudadanos_mediante_un",
        "i19gobierno_digital_servicios_digitales_de_confianza_y_calidad",
        "i20gobierno_digital_fortalecimiento_de_la_arquitectura_empresari",
        "i21gobierno_digital_fortalecimiento_de_la_seguridad_y_privacidad",
        "i82_gobierno_digital_procesos_seguros_y_eficientes",
        "i83_gobierno_digital_toma_de_decisiones_basadas_en_datos",
        "i84_gobierno_digital_impulso_en_el_desarrollo_de_territorios_y_c",
        "i85_gobierno_digital_uso_y_apropiacion_de_los_servicios_ciudadan",
        "i22defensa_juridica_prevencion_del_daño_antijuridico",
        "i24defensa_juridica_gestion_de_los_procesos_judiciales",
        "i27defensa_juridica_capacidad_institucional_para_ejercer_la_defe",
        "i28defensa_juridica_informacion_estratégica_para_la_toma_de_deci",
        "i29transparencia_formulacion_y_seguimiento_al_plan_anticorrupcio",
        "i30transparencia_lucha_contra_la_corrupcion_y_promocion_de_la_in",
        "i31transparencia_gestion_de_riesgos_de_corrupcion",
        "i32transparencia_indice_de_transparencia_y_acceso_a_la_informaci",
        "i33transparencia_divulgacion_proactiva_de_la_informacion",
        "i34transparencia_atencion_apropiada_a_trámites,_peticiones,_quej",
        "i35transparencia_sistema_de_seguimiento_al_acceso_a_la_informaci",
        "i36transparencia_lineamientos_para_el_manejo_y_la_seguridad_de_l",
        "i37transparencia_institucionalizacion_efectiva_de_la_política_de",
        "i38transparencia_gestion_documental_para_el_acceso_a_la_informac",
        "i40transparencia_criterios_diferenciales_de_accesibilidad_a_la_i",
        "i42servicio_al_ciudadano_arreglos_institucionales_implementados",
        "i43servicio_al_ciudadano_procesos_y_procedimientos_para_un_serv",
        "i44servicio_al_ciudadano_fortalecimiento_de_habilidades_y_compr",
        "i45servicio_al_ciudadano_cobertura_de_los_servicios_de_la_entid",
        "i46servicio_al_ciudadano_certidumbre_en_el_servicio",
        "i47servicio_al_ciudadano_cumplimiento_de_expectativas_de_ciudad",
        "i48racionalizacion_de_trámites_identificacion_de_los_trámites_a",
        "i49racionalizacion_de_trámites_priorizacion_de_trámites_con_base",
        "i50racionalizacion_de_trámites_trámites_racionalizados_y_recurso",
        "i51racionalizacion_de_trámites_beneficios_de_las_acciones_de_rac",
        "i52participacion_ciudadana_condiciones_institucionales_idoneas_p",
        "i53participacion_ciudadana_grado_involucramiento_de_ciudadanos_y",
        "i54participacion_ciudadana_calidad_de_la_participacion_ciudadana",
        "i55participacion_ciudadana_eficacia_de_la_participacion_ciudadan",
        "i56participacion_ciudadana_indice_de_rendicion_de_cuentas_en_la",
        "i57participacion_ciudadana_condiciones_institucionales_idoneas_p",
        "i58participacion_ciudadana_informacion_basada_en_resultados_de_g",
        "i59participacion_ciudadana_diálogo_permanente_e_incluyente_en_di",
        "i60participacion_ciudadana_responsabilidad_por_resultados",
        "i61evaluacion_de_resultados_mecanismos_efectivos_de_seguimiento",
        "i62evaluacion_de_resultados_documentacion_del_seguimiento_y_la_e",
        "i63evaluacion_de_resultados_enfoque_en_la_satisfaccion_ciudadana",
        "i64evaluacion_de_resultados_mejoramiento_continuo",
        "i65gestion_documental_calidad_del_componente_estratégico",
        "i66gestion_documental_calidad_del_componente_administracion_de_a",
        "i67gestion_documental_calidad_del_componente_documental",
        "i68gestion_documental_calidad_del_componente_tecnologico",
        "i69gestion_documental_calidad_del_componente_cultural",
        "i87_gestion_del_conocimiento_planeacion_de_la_gestion_del_conoci",
        "i88_gestion_del_conocimiento_generacion_y_produccion_del_conocim",
        "i89_gestion_del_conocimiento_generacion_de_herramientas_de_uso_y",
        "i90_gestion_del_conocimientogeneracion_de_una_cultura_de_propici",
        "i91_gestion_del_conocimientoanalitica_institucional_para_la_toma",
        "i70control_interno_ambiente_propicio_para_el_ejercicio_del_contr",
        "i71control_interno_evaluacion_estratégica_del_riesgo",
        "i72control_interno_actividades_de_control_efectivas",
        "i73control_interno_informacion_y_comunicacion_relevante_y_oportu",
        "i74control_interno_actividades_de_monitoreo_sistemáticas_y_orien",
        "i75control_interno_evaluacion_independiente_al_sistema_de_contro",
        "i77control_interno_linea_estratégica",
        "i78control_interno_primera_linea_de_defensa",
        "i79control_interno_segunda_linea_de_defensa",
        "i80control_interno_tercera_linea_de_defensa",
        "i93_mejora_normativa_planeacion,_diseño_y_consulta_pública",
        "i94_mejora_normativa_norma_final,_seguimiento_y_evaluacion",
        "i95_gestion_de_la_informacion_estadistica_planeacion_estadistica",
        "i96_gestion_de_la_informacion_estadistica_fortalecimiento_de_los",
        "i97_gestion_de_la_informacion_estadistica_calidad_estadistica",
        "indice_de_desempeño_institucional1",
        "d1_talento_humano1",
        "d2direccionamiento_estratégico_y_planeacion",
        "d3_gestion_para_resultados_con valores1",
        "d4_evaluacion_de_resultados1",
        "d5_informacion_y_comunicacion1",
        "d6_gestion_del_conocimiento1",
        "d7_control_interno1",
        "política_1_gestion_estratégica_del_talento_humano1",
        "política_2_integridad1",
        "política_3_planeacion_institucional1",
        "política_4_gestion_presupuestal_y_eficiencia_del_gasto_público1",
        "política_5_fortalecimiento_organizacional_y_simplificacion_de_p1",
        "política_6_gobierno_digital1",
        "política_7_seguridad_digital1",
        "política_8_defensa_juridica1",
        "política_9_transparencia,_acceso_a_la_informacion_y_lucha_contr1",
        "política_10_servicio_al_ciudadano1",
        "política_11_racionalizacion_de_trámites1",
        "política_12_participacion_ciudadana_en_la_gestion_pública1",
        "política_13_seguimiento_y_evaluacion_del_desempeño_instituciona1",
        "política_14_gestion_documental1",
        "política_15_gestion_del_conocimiento1",
        "política_16_control_interno1",
        "política_17_mejora_normativa1",
        "política_18_gestion_de_la_informacion_estadistica1",
        "indice_de_desempeño_institucional2",
        "d1_talento_humano2",
        "d2direccionamiento_estratégico_y_planeacion1",
        "d3_gestion_para_resultados_con valores2",
        "d4_evaluacion_de_resultados2",
        "d5_informacion_y_comunicacion2",
        "d6_gestion_del_conocimiento2",
        "d7_control_interno2",
        "política_1_gestion_estratégica_del_talento_humano2",
        "política_2_integridad2",
        "política_3_planeacion_institucional2",
        "política_4_gestion_presupuestal_y_eficiencia_del_gasto_público2",
        "política_5_fortalecimiento_organizacional_y_simplificacion_de_p2",
        "política_6_gobierno_digital2",
        "política_7_seguridad_digital2",
        "política_8_defensa_juridica2",
        "política_9_transparencia,_acceso_a_la_informacion_y_lucha_contr2",
        "política_10_servicio_al_ciudadano2",
        "política_11_racionalizacion_de_trámites2",
        "política_12_participacion_ciudadana_en_la_gestion_pública2",
        "política_13_seguimiento_y_evaluacion_del_desempeño_instituciona2",
        "política_14_gestion_documental2",
        "política_15_gestion_del_conocimiento2",
        "política_16_control_interno2",
        "política_17_mejora_normativa2",
        "política_18_gestion_de_la_informacion_estadistica2",
        "indice_de_desempeño_institucional3",
        "d1_talento_humano3",
        "d2direccionamiento_estratégico_y_planeacion2",
        "d3_gestion_para_resultados_con valores3",
        "d4_evaluacion_de_resultados3",
        "d5_informacion_y_comunicacion3",
        "d6_gestion_del_conocimiento3",
        "d7_control_interno3",
        "política_1_gestion_estratégica_del_talento_humano3",
        "política_2_integridad3",
        "política_3_planeacion_institucional3",
        "política_4_gestion_presupuestal_y_eficiencia_del_gasto_público3",
        "política_5_fortalecimiento_organizacional_y_simplificacion_de_p3",
        "política_6_gobierno_digital3",
        "política_7_seguridad_digital3",
        "política_8_defensa_juridica3",
        "política_9_transparencia,_acceso_a_la_informacion_y_lucha_contr3",
        "política_10_servicio_al_ciudadano3",
        "política_11_racionalizacion_de_trámites3",
        "política_12_participacion_ciudadana_en_la_gestion_pública3",
        "política_13_seguimiento_y_evaluacion_del_desempeño_instituciona3",
        "política_14_gestion_documental3",
        "política_15_gestion_del_conocimiento3",
        "política_16_control_interno3",
        "política_17_mejora_normativa3",
        "política_18_gestion_de_la_informacion_estadistica3",
        "indice_de_desempeño_institucional4",
        "d1_talento_humano4",
        "d2direccionamiento_estratégico_y_planeacion3",
        "d3_gestion_para_resultados_con valores4",
        "d4_evaluacion_de_resultados4",
        "d5_informacion_y_comunicacion4",
        "d6_gestion_del_conocimiento4",
        "d7_control_interno4",
        "política_1_gestion_estratégica_del_talento_humano4",
        "política_2_integridad4",
        "política_3_planeacion_institucional4",
        "política_4_gestion_presupuestal_y_eficiencia_del_gasto_público4",
        "política_5_fortalecimiento_organizacional_y_simplificacion_de_p4",
        "política_6_gobierno_digital4",
        "política_7_seguridad_digital4",
        "política_8_defensa_juridica4",
        "política_9_transparencia,_acceso_a_la_informacion_y_lucha_contr4",
        "política_10_servicio_al_ciudadano4",
        "política_11_racionalizacion_de_trámites4",
        "política_12_participacion_ciudadana_en_la_gestion_pública4",
        "política_13_seguimiento_y_evaluacion_del_desempeño_instituciona4",
        "política_14_gestion_documental4",
        "política_15_gestion_del_conocimiento4",
        "política_16_control_interno4",
        "política_17_mejora_normativa4",
        "política_18_gestion_de_la_informacion_estadistica4",
        "created_at",
        "updated_at",
        "deleted_at",
        "author",
    ];
    protected $useTimestamps = true;
    protected $createdField = "created_at";
    protected $updatedField = "updated_at";
    protected $deletedField = "deleted_at";
    protected $validationRules = [];
    protected $validationMessages = [];
    protected $skipValidation = false;
    protected $DBGroup = "authentication"; //default

    /**
     * Retorna falso o verdadero si el usuario activo ne la sesión es el
     * autor del regsitro que se desea acceder, editar o eliminar.
     * @param type $id codigo primario del registro a consultar
     * @param type $author codigo del usuario del cual se pretende establecer la autoria
     * @return boolean falso o verdadero segun sea el caso
     */
    public function get_Authority($id, $author)
    {
        $row = $this->where("author", $id)->first();
        if (@$row["author"] == $author) {
            return (true);
        } else {
            return (false);
        }
    }

}

?>